// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageApi.Data;

#nullable disable

namespace StorageApi.Migrations
{
    [DbContext(typeof(StorageApiContext))]
    [Migration("20250626192144_CreateProducts")]
    partial class CreateProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StorageApi.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shelf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Count = 15,
                            Description = "Ergonomic mouse with 2.4 GHz receiver.",
                            Name = "Wireless Mouse",
                            Price = 299,
                            Shelf = "E1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Count = 30,
                            Description = "20W fast charger, compatible with most phones.",
                            Name = "USB-C Charger",
                            Price = 199,
                            Shelf = "E2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sports",
                            Count = 12,
                            Description = "Non-slip exercise mat made of durable material.",
                            Name = "Yoga Mat",
                            Price = 349,
                            Shelf = "S3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Office",
                            Count = 50,
                            Description = "80 pages, lined with soft cover.",
                            Name = "Notebook A5",
                            Price = 79,
                            Shelf = "O1"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Kitchen",
                            Count = 40,
                            Description = "Ceramic cup 300 ml, dishwasher safe.",
                            Name = "Coffee Mug",
                            Price = 99,
                            Shelf = "K2"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Count = 20,
                            Description = "HDMI 2.1 supporting 4K and 8K.",
                            Name = "HDMI Cable 2m",
                            Price = 149,
                            Shelf = "E3"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sports",
                            Count = 18,
                            Description = "Safety vest for running or cycling.",
                            Name = "Reflective Vest",
                            Price = 129,
                            Shelf = "S4"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Office",
                            Count = 25,
                            Description = "Multi-purpose scissors with ergonomic grip.",
                            Name = "Scissors",
                            Price = 59,
                            Shelf = "O2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
